# Generated by Django 5.2.4 on 2025-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=10),
        ),
    ]
